"""empty message

Revision ID: a44e09b59c08
Revises: 
Create Date: 2024-07-23 17:55:45.766427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44e09b59c08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.String(length=128), nullable=False),
    sa.Column('user_password', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('user_lastname', sa.String(length=128), nullable=False),
    sa.Column('user_privileges', sa.String(length=128), nullable=False),
    sa.Column('user_state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_region_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=False),
    sa.Column('site_segment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('routers',
    sa.Column('router_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('router_name', sa.String(length=128), nullable=False),
    sa.Column('router_description', sa.String(length=256), nullable=False),
    sa.Column('router_brand', sa.String(length=128), nullable=False),
    sa.Column('router_model', sa.String(length=128), nullable=False),
    sa.Column('fk_site_id', sa.Integer(), nullable=False),
    sa.Column('router_ip', sa.String(length=16), nullable=False),
    sa.Column('router_mac', sa.String(length=32), nullable=False),
    sa.Column('router_username', sa.String(length=128), nullable=False),
    sa.Column('router_password', sa.String(length=128), nullable=False),
    sa.Column('allow_scan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('router_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routers')
    op.drop_table('sites')
    op.drop_table('users')
    op.drop_table('regions')
    # ### end Alembic commands ###
