"""Sites Section

Revision ID: a9a52bb945aa
Revises: df88bc72f94a
Create Date: 2024-07-21 23:08:25.431858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a52bb945aa'
down_revision = 'df88bc72f94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_region_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=False),
    sa.Column('site_segment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###
