"""Routers Section

Revision ID: fb76bcf09f97
Revises: a9a52bb945aa
Create Date: 2024-07-22 15:44:48.001914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb76bcf09f97'
down_revision = 'a9a52bb945aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routers',
    sa.Column('router_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('router_name', sa.String(length=128), nullable=False),
    sa.Column('router_description', sa.String(length=256), nullable=False),
    sa.Column('router_brand', sa.String(length=128), nullable=False),
    sa.Column('router_model', sa.String(length=128), nullable=False),
    sa.Column('fk_site_id', sa.Integer(), nullable=False),
    sa.Column('router_ip', sa.String(length=16), nullable=False),
    sa.Column('router_mac', sa.String(length=32), nullable=False),
    sa.Column('router_username', sa.String(length=128), nullable=False),
    sa.Column('router_password', sa.String(length=128), nullable=False),
    sa.Column('allow_scan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('router_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routers')
    # ### end Alembic commands ###
